// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserMessage {
    #[prost(fixed64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub to_id: u64,
    #[prost(uint64, tag="3")]
    pub from_id: u64,
    #[prost(bytes="vec", tag="4")]
    pub text: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="6")]
    pub r#type: u32,
    /// flags for server to notify or just send or don't send
    #[prost(uint32, tag="7")]
    pub settings: u32,
    /// optional sends these for decryption purposes
    #[prost(string, tag="8")]
    pub from_username: ::prost::alloc::string::String,
    #[prost(uint32, tag="9")]
    pub from_device_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Group {
    #[prost(fixed64, tag="1")]
    pub id: u64,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="6")]
    pub settings: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Groups {
    #[prost(message, repeated, tag="1")]
    pub groups: ::prost::alloc::vec::Vec<Group>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserMessages {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<UserMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupInvite {
    #[prost(uint64, tag="1")]
    pub group_id: u64,
    #[prost(string, tag="2")]
    pub inviter: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub invitee: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub welcome_message: ::prost::alloc::vec::Vec<u8>,
    #[prost(fixed64, tag="5")]
    pub commit_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupCommitAndWelcome {
    #[prost(fixed64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub group_id: u64,
    #[prost(bytes="vec", tag="3")]
    pub commit_message: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub inviter: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub invitee: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub welcome_message: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag="7")]
    pub invitee_addresses: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupInvites {
    #[prost(message, repeated, tag="1")]
    pub invites: ::prost::alloc::vec::Vec<GroupInvite>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupMessage {
    #[prost(fixed64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub group_id: u64,
    #[prost(bytes="vec", tag="3")]
    pub message: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="4")]
    pub epoch: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupKeyPackage {
    #[prost(uint64, tag="3")]
    pub address: u64,
    #[prost(bytes="vec", tag="2")]
    pub package: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub username: ::prost::alloc::string::String,
    #[prost(int32, tag="1")]
    pub id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupKeyPackages {
    #[prost(message, repeated, tag="1")]
    pub packages: ::prost::alloc::vec::Vec<GroupKeyPackage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMessages {
    #[prost(message, repeated, tag="2")]
    pub messages: ::prost::alloc::vec::Vec<GroupMessage>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupSyncRequest {
    #[prost(uint64, tag="1")]
    pub group_id: u64,
    #[prost(fixed64, tag="2")]
    pub start_after: u64,
    #[prost(fixed64, tag="3")]
    pub until: u64,
    #[prost(uint32, tag="4")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupSyncRequests {
    #[prost(message, repeated, tag="1")]
    pub requests: ::prost::alloc::vec::Vec<GroupSyncRequest>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupMemberUpdate {
    #[prost(uint64, tag="1")]
    pub group_id: u64,
    #[prost(fixed64, tag="2")]
    pub last_message_seen: u64,
    #[prost(uint32, tag="3")]
    pub last_epoch: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMemberUpdates {
    #[prost(message, repeated, tag="1")]
    pub updates: ::prost::alloc::vec::Vec<GroupMemberUpdate>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupCommit {
    #[prost(fixed64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub group_id: u64,
    #[prost(bytes="vec", tag="4")]
    pub commit: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="3")]
    pub epoch: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupCommits {
    #[prost(message, repeated, tag="1")]
    pub commits: ::prost::alloc::vec::Vec<GroupCommit>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupCommitSyncRequest {
    #[prost(uint64, tag="1")]
    pub group_id: u64,
    #[prost(uint32, tag="2")]
    pub epoch: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupReAddRequest {
    #[prost(uint64, tag="1")]
    pub group_id: u64,
    #[prost(uint64, tag="2")]
    pub address_id: u64,
    #[prost(string, tag="3")]
    pub username: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupReAddRequests {
    #[prost(message, repeated, tag="1")]
    pub requests: ::prost::alloc::vec::Vec<GroupReAddRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag="2")]
    pub error: ::prost::alloc::string::String,
    #[prost(uint32, tag="1")]
    pub error_code: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Result {
    #[prost(bytes="vec", tag="2")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="1")]
    pub result_code: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub fcm_token: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub device_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Addresses {
    #[prost(message, repeated, tag="1")]
    pub addresses: ::prost::alloc::vec::Vec<Address>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadUserMessage {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<UserMessage>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageIdAndTo {
    #[prost(fixed64, tag="1")]
    pub id: u64,
    #[prost(uint64, tag="2")]
    pub to: u64,
    #[prost(bool, tag="3")]
    pub is_self: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserMessageUploaded {
    #[prost(message, repeated, tag="1")]
    pub message_ids: ::prost::alloc::vec::Vec<MessageIdAndTo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(oneof="request::Payload", tags="2, 3, 4")]
    pub payload: ::core::option::Option<request::Payload>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag="2")]
        CreateUserMessage(super::UserMessage),
        #[prost(message, tag="3")]
        UploadUserMessage(super::UploadUserMessage),
        #[prost(message, tag="4")]
        UploadGroupMessage(super::GroupMessage),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(message, optional, tag="2")]
    pub error: ::core::option::Option<Error>,
    #[prost(oneof="response::Body", tags="3, 4, 5")]
    pub body: ::core::option::Option<response::Body>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag="3")]
        CreatedUserMessage(super::UserMessage),
        #[prost(message, tag="4")]
        UserMessageUploaded(super::UserMessageUploaded),
        #[prost(message, tag="5")]
        GroupMessageUploaded(super::GroupMessage),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(oneof="server_message::Message", tags="1, 2, 3, 4, 10, 11, 12")]
    pub message: ::core::option::Option<server_message::Message>,
}
/// Nested message and enum types in `ServerMessage`.
pub mod server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        UserMessage(super::UserMessage),
        #[prost(message, tag="2")]
        GroupMessage(super::GroupMessage),
        #[prost(message, tag="3")]
        UserMessages(super::UserMessages),
        #[prost(message, tag="4")]
        GroupMessages(super::GroupMessages),
        #[prost(message, tag="10")]
        Response(super::Response),
        #[prost(bytes, tag="11")]
        Ping(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes, tag="12")]
        Pong(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof="client_message::Message", tags="1, 2, 10, 11, 12")]
    pub message: ::core::option::Option<client_message::Message>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        UserMessage(super::UserMessage),
        #[prost(message, tag="2")]
        GroupMessage(super::GroupMessage),
        #[prost(message, tag="10")]
        Request(super::Request),
        #[prost(bytes, tag="11")]
        Ping(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes, tag="12")]
        Pong(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroupId {
    #[prost(uint64, tag="2")]
    pub id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthToken {
    #[prost(string, tag="1")]
    pub username: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub valid_until: u64,
    #[prost(bytes="vec", tag="4")]
    pub credential: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="6")]
    pub address_id: u64,
    #[prost(uint32, tag="5")]
    pub device_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedToken {
    #[prost(string, tag="1")]
    pub kid: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FireflyIdentity {
    #[prost(bytes="vec", tag="2")]
    pub secret: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub public: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub credential: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FireflyGroupExtension {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub roles: ::prost::alloc::vec::Vec<FireflyGroupRole>,
    #[prost(message, repeated, tag="3")]
    pub channels: ::prost::alloc::vec::Vec<FireflyGroupChannel>,
    #[prost(message, repeated, tag="4")]
    pub members: ::prost::alloc::vec::Vec<FireflyGroupMember>,
    #[prost(fixed32, tag="5")]
    pub default_permissions: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FireflyGroupRole {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(fixed32, tag="3")]
    pub permissions: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FireflyGroupMember {
    #[prost(string, tag="1")]
    pub username: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub role: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FireflyGroupChannel {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub r#type: u32,
    #[prost(message, repeated, tag="4")]
    pub roles: ::prost::alloc::vec::Vec<FireflyGroupRole>,
    #[prost(fixed32, tag="5")]
    pub default_permissions: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreKeyBundle {
    #[prost(uint32, tag="1")]
    pub registration_id: u32,
    #[prost(uint32, tag="2")]
    pub device_id: u32,
    #[prost(uint32, tag="3")]
    pub pre_key_id: u32,
    #[prost(bytes="vec", tag="4")]
    pub pre_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub signed_pre_key_id: u32,
    #[prost(bytes="vec", tag="6")]
    pub signed_pre_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub signed_pre_key_signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub identity_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="9")]
    pub kem_pre_key_id: u32,
    #[prost(bytes="vec", tag="10")]
    pub kem_pre_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub kem_pre_key_signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreKeyBundleEntry {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(uint64, tag="2")]
    pub address: u64,
    #[prost(message, optional, tag="3")]
    pub bundle: ::core::option::Option<PreKeyBundle>,
    #[prost(string, tag="4")]
    pub username: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub device_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreKeyBundleEntries {
    #[prost(message, repeated, tag="1")]
    pub entries: ::prost::alloc::vec::Vec<PreKeyBundleEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationStart {
    #[prost(uint64, tag="1")]
    pub conversation_id: u64,
    #[prost(string, tag="2")]
    pub started_by: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub other: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub bundle: ::core::option::Option<PreKeyBundle>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreKeyBundles {
    #[prost(message, repeated, tag="1")]
    pub bundles: ::prost::alloc::vec::Vec<PreKeyBundle>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Conversation {
    #[prost(string, tag="1")]
    pub user1: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user2: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub settings: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conversations {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptedFile {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub secret_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub content_type: u32,
    #[prost(uint32, tag="4")]
    pub content_length: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncryptedFiles {
    #[prost(message, repeated, tag="1")]
    pub files: ::prost::alloc::vec::Vec<EncryptedFile>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePayload {
    #[prost(string, tag="1")]
    pub text: ::prost::alloc::string::String,
    #[prost(fixed64, tag="2")]
    pub replying_to: u64,
    #[prost(message, optional, tag="3")]
    pub files: ::core::option::Option<EncryptedFiles>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CallMessage {
    #[prost(bytes="vec", tag="1")]
    pub message: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration="CallMessageType", tag="3")]
    pub r#type: i32,
    #[prost(string, tag="4")]
    pub json_body: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub session_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelfUserMessage {
    #[prost(string, tag="1")]
    pub to: ::prost::alloc::string::String,
    /// UserMessageInner encrypted
    #[prost(bytes="vec", tag="2")]
    pub inner: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserMessageInner {
    #[prost(oneof="user_message_inner::Message", tags="1, 2, 3, 4")]
    pub message: ::core::option::Option<user_message_inner::Message>,
}
/// Nested message and enum types in `UserMessageInner`.
pub mod user_message_inner {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(bytes, tag="1")]
        PlainText(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag="2")]
        CallMessage(super::CallMessage),
        #[prost(message, tag="3")]
        MessagePayload(super::MessagePayload),
        #[prost(message, tag="4")]
        SelfMessage(super::SelfUserMessage),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMessageInner {
    #[prost(uint32, tag="1")]
    pub channel_id: u32,
    #[prost(oneof="group_message_inner::Message", tags="2")]
    pub message: ::core::option::Option<group_message_inner::Message>,
}
/// Nested message and enum types in `GroupMessageInner`.
pub mod group_message_inner {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="2")]
        MessagePayload(super::MessagePayload),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallMessageType {
    None = 0,
    Request = 1,
    Reject = 2,
    End = 3,
    /// for saving call messages
    Ended = 4,
    Rejected = 5,
    /// webrtc messages
    Candidate = 10,
    Answer = 11,
    Offer = 12,
}
impl CallMessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Request => "request",
            Self::Reject => "reject",
            Self::End => "end",
            Self::Ended => "ended",
            Self::Rejected => "rejected",
            Self::Candidate => "candidate",
            Self::Answer => "answer",
            Self::Offer => "offer",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "none" => Some(Self::None),
            "request" => Some(Self::Request),
            "reject" => Some(Self::Reject),
            "end" => Some(Self::End),
            "ended" => Some(Self::Ended),
            "rejected" => Some(Self::Rejected),
            "candidate" => Some(Self::Candidate),
            "answer" => Some(Self::Answer),
            "offer" => Some(Self::Offer),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
